### ISSUE TITLE
implement queen

### ISSUE THREAD

**Issue by ProfNorm** [MichaelMrt03/ChessPHP#22]

**Comment by MichaelMrt03** [comment]
lets make the queen after rook and bishop and make an interface for that

**Comment by MichaelMrt03** [comment]
Interface is the wrong idea.
But it can be made with traits.

We have to define a trait like 
_check_move_diagonally_ for bishop
and
_check_move_horizontally_ for rook.

Then we can use the traits in Queen to save some codelines
